Update ActionSubscriber to reduce Fluxor.DisposableCallbacks
mrpmorris/Fluxor pull request #379
Opened 2022-12-07 08:50 UTC by sallyjwhite

We have a production version of Blazor Server running on Azure, that extensively uses Fluxor. We were investigating a memory leak and have found that the application is holding on to Flxuor Subscriptions preventing the subscription from being removed through the GC.
Memory analysis report shows 15K Fluxor.DisposableCallbacks in the "Finalizable objects require multiple garbage collection to clean up and may cause performance issues" after 15 hours of up time and a maximum of 40 users.
With this change it drops to around 700.
This wasn't the cause our memory leak. Our memory leak prevented the whole session from being disposed. This meant before the memory leak was resolved, we had 250K instances of Fluxor.DisposableCallbacks which is what led us to investigate in the first place

2022-12-08 09:22 UTC, mrpmorris requested changes
While you are in here, would you mind tidying up a couple of things for me, please?
Fluxor.Extensions and System.Threading are in the `uses` clauses at the top but not used, would you mind removing those?

Also, there are 2 blank lines before the GetActionUnsubscriberAsIDisposable method, would you mind changing it to 1 for me?

Thank you!

2022-12-08 09:22 UTC, mrpmorris commented on Source/Lib/Fluxor/ActionSubscriber.cs
> +				    instanceSubscriptions
Please replace space indentation with tabs.

2022-12-08 09:22 UTC, mrpmorris commented on Source/Lib/Fluxor/ActionSubscriber.cs
> +					SubscriptionsForInstance.Remove(subscription);
You don't need to use ContainsKey before Remove as Remove will fail silently when the key does not exist and return `false` which we can ignore.  Also, please ensure the indentation is tabs only, not spaces.

2022-12-09 09:36 UTC, mrpmorris commented
Hi

You've replaced tabs with spaces, I wanted the opposite. I use tabs :)

2022-12-09 10:28 UTC, sallyjwhite commented
Hope that's sorted it - seems to be messing up the formatting when updated on githib

2022-12-09 12:52 UTC, mrpmorris commented
Merged into 5.7 - thank you for your help!

2022-12-09 12:52 UTC, closed without merging